### ISSUE TITLE
fatal: detected dubious ownership in repository at '/github/workspace'

### ISSUE THREAD

**Issue by ljubon** [jaumann/github-bumpversion-action#10]
When running with default settings on latest `ubuntu-latest` i get following error

```yaml
      - name: Check out code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: jaumann/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
```
From job output, following error is shown

```
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
```
